# Generated by Django 4.0.4 on 2022-05-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('conent', models.CharField(max_length=1000)),
                ('date_posted', models.DateField()),
                ('no_likes', models.IntegerField()),
            ],
        ),
    ]
