# Generated by Django 4.0.4 on 2022-05-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0003_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='article',
            field=models.ManyToManyField(to='demo_app.article'),
        ),
    ]
