# Generated by Django 4.0.4 on 2022-05-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0006_article_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=40)),
                ('no_pages', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
